# Change these first
owner: cocredo # Your GitHub organization or username, where this repository lives
repo: cocredo-status # The name of this repository

sites:
  - name: CoCredo Website
    url: https://www.cocredo.co.uk
  - name: Quick Credit Reports
    url: https://www.quickcreditreports.co.uk
  - name: CoCredo API
    url: https://apigw.cocredo.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /cocredo-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CoCredo Service Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /cocredo-status
    - title: GitHub
      href: https://www.cocredo.co.uk/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
